### PR TITLE
Add command to list locales used in a project

### PR DESCRIPTION
**Pull request by WouterSioen**
This way we can more easily download all locales in a cli script (fetch
them using this command and then download in a loop)

### CODE REVIEW

**Comment by WouterSioen** [comment]
@jenssegers @luisabritotl @JordyDeGroeve @mrnnn @mrtus 

I can't assign reviewers, but I'll try to get this merged this way 😅

**Comment by WouterSioen** [comment]
Note: this would also require a new release to be able to use it.

**Comment by WouterSioen** [comment]
@JordyDeGroeve https://github.com/teamleadercrm/onesky-cli/pull/7/files#diff-f960e1fa1397329e8370e4bec3547229R16 explains it.

But I mostly used the same structure as other commands, just calling anoter api endpoint on the onesky api.

**Comment by mrtus** [comment]
@mrnnn Can the developer team be added this repo? We shouldn't be forking our repos to be able to make changes.

**Comment by Steerlin** [comment]
@mrnnn can I be removed pls ?

**Pull request merged**
